spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: syspass
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
---
app:
  token:
    secret: GameExchange#MySecret2024GGWP
    issuer: javabachend
